### ISSUE TITLE
Waypoint tile cannot be moved or hidden, blocking view of field and making waypoints unclickable

### ISSUE THREAD

**Issue by Navigator365** [mjansen4857/pathplanner#65] opened 2022-01-29 19:57 UTC
When editing a waypoint, an unmovable tile pops up, blocking view of the upper-right corner of the field. Clicking on a point in the upper-right hand corner makes it impossible to drag-edit portions of it that overlap with the tile, and blocks view of that waypoint on the field.

Here's an example of the issue-it's impossible to manually drag the endpoint or adjust its control points. Additionally, resizing the window does not fully solve the problem, as the waypoint is still partially obscured. 
<img width="960" alt="examplepath" src="https://user-images.githubusercontent.com/40570437/151675517-59de3a3e-b63d-47a0-8da6-c2c6a3f49a7e.PNG">

**Comment by mjansen4857** [comment] 2022-01-30 00:45
I'm going to close this and consider it a duplicate of #60 as the solution to both of them is the same. Also, you can make the window shorter to move the tile out of the way:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/9343077/151682440-9f69e86d-5ae3-4107-a51f-5d64d9d97d9c.png">
It's not ideal but it works for now. You could also make all of your paths on the blue side of the field since the field is symmetric.

**Closed by mjansen4857** 2022-01-30 00:45 UTC
