### ISSUE TITLE
Light mode in GUI? Or other easy way to print out auto paths?

### ISSUE THREAD

**Issue by Chris857** [mjansen4857/pathplanner#702] opened 2024-06-29 20:21 UTC
Last year we printed a page of our auto modes from path planner so we could show them during match planning. One annoyance was that the pathplanner GUI seems to only have dark mode, so it took a bit of photoshop work to get a white background to print nicely.

Would it be possible to add light mode to the GUI, or to otherwise make printing images of the auto paths more convenient?

**Comment by qrAIhttps** [comment] 2024-07-25 19:46
I would love to actually see a print function, especially one that prints the whole field

**Comment by mjansen4857** [comment] 2024-09-25 19:22
Duplicate of #642

**Closed by mjansen4857** 2024-09-25 19:22 UTC
Labels: enhancement
