### ISSUE TITLE
Try to run on Mac but crashes when opening

### ISSUE THREAD

**Issue by kinahawi** [mjansen4857/pathplanner#362] opened 2023-10-05 02:24 UTC
When I try to run the program, it attempts to start, but then closes unexpectedly. No error  message is given. Tried uninstall and reinstall but no luck. MacBook Pro running Ventura 13.5.2

**Comment by jonahsnider** [comment] 2023-10-05 04:00
Duplicate of #360?

**Comment by mjansen4857** [comment] 2023-10-05 15:01
The main branch is not released. Do the terminal command in the last comment of #360

**Comment by kinahawi** [comment] 2023-10-05 16:54
Thanks. I didn’t recognize that as a terminal command. That seems to have fixed it.

**Closed** 2023-10-05 17:39 UTC
